pub const DISCRIMINATOR_LENGTH: usize = 8;
pub const PUBLIC_KEY_LENGTH: usize = 32;
pub const TIMESTAMP_LENGTH: usize = 8;
pub const STRING_LENGTH_PREFIX: usize = 4;
pub const VECTOR_LENGTH_PREFIX: usize = 4;
pub const MAX_PROTOCOL_LENGTH: usize = 50 * 4; // 50 chars max.
pub const MIN_GPG_LENGTH: usize = 2048 * 4; // 280 chars max.
pub const MAX_GPG_LENGTH: usize = 4096 * 4; // 280 chars max.
pub const BUMP_LENGTH: usize = 1;
pub const SEED_LENGTH: usize = 4;
